# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Touraty' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Touraty
  
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'TouratyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TouratyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
